#!/bin/bash

# ==========================================================
# .env (config.env) 作成用対話型スクリプト
# ==========================================================

# 実行場所に関わらずプロジェクトルートを基準にする
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

CONFIG_FILE="config.env"
EXAMPLE_FILE="config.env.example"

# 既存の設定ファイルがある場合はバックアップ
if [ -f "$CONFIG_FILE" ]; then
    echo "$CONFIG_FILE は既に存在します。"
    read -p "上書きしますか？ (y/n): " confirm
    if [ "$confirm" != "y" ]; then
        echo "中断しました。"
        exit 1
    fi
    cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"
    echo "既存の $CONFIG_FILE を ${CONFIG_FILE}.bak にバックアップしました。"
fi

echo "----------------------------------------------------------"
echo "バックアップ設定 (config.env) を作成します。"
echo "Enterを押すと [ ] 内のデフォルト値が使用されます。"
echo "----------------------------------------------------------"

# 入力補助関数
ask() {
    local prompt=$1
    local var_name=$2
    local default_value=$3
    local input

    read -p "$prompt [$default_value]: " input
    if [ -z "$input" ]; then
        eval "$var_name=\"$default_value\""
    else
        eval "$var_name=\"$input\""
    fi
}

# --- 最低限設定するもの (必須級) ---
echo ""
echo "[1/2] 最低限設定が必要な項目"
echo "----------------------------------------------------------"

ask "サービス名 (app-name)" "SERVICE_NAME" "app-name"
ask "環境識別 (production/staging/development)" "ENVIRONMENT" "production"
ask "DBホスト名" "DB_HOST" "localhost"
ask "DBポート番号" "DB_PORT" "3306"
ask "DB名" "DB_NAME" "your_database"
ask "DBユーザー名" "DB_USER" "backup_user"
read -s -p "DBパスワード: " DB_PASS
echo ""
[ -z "$DB_PASS" ] && DB_PASS="your_password_here"

ask "Laravelアプリのルートディレクトリ" "APP_DIR" "/var/www/your-app"
ask "ローカルバックアップ保存先" "BACKUP_LOCAL_DIR" "/backup"
ask "ローカル保持世代数" "KEEP_GENERATIONS" "30"

# --- 必要に応じて設定するもの (オプション) ---
echo ""
echo "[2/2] 必要に応じて設定する項目 (Enterでデフォルト/空)"
echo "----------------------------------------------------------"

ask "追加バックアップディレクトリ (スペース区切り)" "EXTRA_BACKUP_DIRS" ""
ask "サーバー設定バックアップ対象" "CONFIG_BACKUP_DIRS" "/etc/nginx /etc/php"
ask "ストレージバックエンド (s3/wasabi/sakura/idrive/local)" "STORAGE_BACKEND" "local"

if [ "$STORAGE_BACKEND" != "local" ]; then
    ask "ストレージバケット名" "STORAGE_BUCKET" "your-backup-bucket"
    ask "バケット内プレフィックス" "STORAGE_PREFIX" "backups/server1"
    
    echo ""
    echo "--- AWS / S3 互換ストレージの認証情報 ---"
    ask "AWS Access Key ID" "AWS_ACCESS_KEY_ID" ""
    read -s -p "AWS Secret Access Key: " AWS_SECRET_ACCESS_KEY
    echo ""
    ask "AWS Default Region" "AWS_DEFAULT_REGION" "ap-northeast-1"
    
    if [ "$STORAGE_BACKEND" != "s3" ]; then
        ask "S3 互換エンドポイント URL (例: https://s3.wasabisys.com)" "S3_ENDPOINT_URL" ""
    else
        S3_ENDPOINT_URL=""
    fi
    
    ask "バケットが存在しない場合に新規作成しますか？ (y/n)" "CREATE_BUCKET" "n"
fi

ask "通知先メールアドレス" "NOTIFY_EMAIL" ""
ask "通知用 Webhook URL" "WEBHOOK_URL" ""

# --- config.env の作成 ---
cat << EOF > "$CONFIG_FILE"
# ==========================================================
# バックアップ設定ファイル (Generated by setup_env.sh)
# ==========================================================

# ----- 環境識別 -----
# バックアップファイル名・ログに付与される識別子
SERVICE_NAME=$SERVICE_NAME
ENVIRONMENT=$ENVIRONMENT

# ----- データベース -----
DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASS='$DB_PASS'

# ----- バックアップ対象ディレクトリ -----
# Laravelアプリケーションのルートディレクトリ
APP_DIR=$APP_DIR

# 追加でバックアップするディレクトリ（スペース区切り、不要なら空にする）
EXTRA_BACKUP_DIRS="$EXTRA_BACKUP_DIRS"

# サーバー設定ファイルのバックアップ（スペース区切り）
CONFIG_BACKUP_DIRS="$CONFIG_BACKUP_DIRS"

# ----- ローカルバックアップ設定 -----
BACKUP_LOCAL_DIR=$BACKUP_LOCAL_DIR
KEEP_GENERATIONS=$KEEP_GENERATIONS

# ----- Cron スケジュール -----
# cron形式: 分 時 日 月 曜日
CRON_MYSQL="0 2 * * *"          # MySQLバックアップ（毎日 2:00）
CRON_FILES="0 3 * * *"          # ファイルバックアップ（毎日 3:00）
CRON_SYNC="0 4 * * *"           # クラウド同期（毎日 4:00）

# ----- ストレージバックエンド -----
# 選択肢: s3 / wasabi / sakura / idrive / local
STORAGE_BACKEND=$STORAGE_BACKEND

# バケット名
STORAGE_BUCKET=$STORAGE_BUCKET

# バケット内のプレフィックス（サーバー識別用フォルダ名）
STORAGE_PREFIX=$STORAGE_PREFIX

# ----- AWS S3 / S3 互換ストレージ設定 -----
# 公式 CLI (aws s3) を直接実行します。
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY='$AWS_SECRET_ACCESS_KEY'
AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

# S3 互換ストレージの場合のエンドポイント URL
# AWS S3 の場合は空にしてください。
S3_ENDPOINT_URL=$S3_ENDPOINT_URL

# セットアップ時にバケットを新規作成するか (y/n)
CREATE_BUCKET=$CREATE_BUCKET

# ----- 通知設定 -----
# 通知先メールアドレス
NOTIFY_EMAIL=$NOTIFY_EMAIL

# SendGrid (APIを利用する場合)
SENDGRID_API_KEY=
SENDGRID_FROM_EMAIL=

# チャットツール Webhook URL (Slack, Mattermost 等)
WEBHOOK_URL=$WEBHOOK_URL

# ----- テストDBリストアチェック -----
# バックアップが正しくリストアできるか定期的に検証するためのDB
TEST_DB_NAME=${SERVICE_NAME}_test

# テストDBの接続情報 (指定しない場合は本番DBと同じ設定を使用します)
TEST_DB_HOST=
TEST_DB_PORT=
TEST_DB_USER=
TEST_DB_PASS=

CRON_TEST_RESTORE="0 5 * * *"     # テストリストア実行（毎日 5:00）

# ----- ログ設定 -----
LOG_DIR=/var/log/backup

# ----- リストア設定 (MySQLのみ) -----
# リストア時に実行するマスク用SQLファイルのパス
# 例: MASK_SQL_FILE="scripts/mask_data.sql"
MASK_SQL_FILE=""

# リストア開始前に停止し、完了後に起動するサービス名（スペース区切り）
# 例: RESTORE_STOP_SERVICES="nginx php8.3-fpm"
RESTORE_STOP_SERVICES=""
EOF

echo ""
echo "----------------------------------------------------------"
echo "$CONFIG_FILE を作成しました。"
echo "詳細な設定（S3キーやSendGrid API等）は直接ファイルを編集してください。"
echo "----------------------------------------------------------"
