#!/bin/bash

# ==========================================================
# .env (config.env) 作成用対話型スクリプト
# ==========================================================

# 実行場所に関わらずプロジェクトルートを基準にする
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

CONFIG_FILE="config.env"
EXAMPLE_FILE="config.env.example"

# 既存の設定ファイルがある場合はバックアップ
if [ -f "$CONFIG_FILE" ]; then
    echo "$CONFIG_FILE は既に存在します。"
    read -p "上書きしますか？ (y/n): " confirm
    if [ "$confirm" != "y" ]; then
        echo "中断しました。"
        exit 1
    fi
    cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"
    echo "既存の $CONFIG_FILE を ${CONFIG_FILE}.bak にバックアップしました。"
fi

echo "----------------------------------------------------------"
echo "バックアップ設定 (config.env) を作成します。"
echo "Enterを押すと [ ] 内のデフォルト値が使用されます。"
echo "----------------------------------------------------------"

# 入力補助関数
ask() {
    local prompt=$1
    local var_name=$2
    local default_value=$3
    local input

    read -p "$prompt [$default_value]: " input
    if [ -z "$input" ]; then
        eval "$var_name=\"$default_value\""
    else
        eval "$var_name=\"$input\""
    fi
}

# --- 最低限設定するもの (必須級) ---
echo ""
echo "[1/2] 最低限設定が必要な項目"
echo "----------------------------------------------------------"

ask "サービス名 (app-name)" "SERVICE_NAME" "app-name"
ask "環境識別 (production/staging/development)" "ENVIRONMENT" "production"
ask "DBホスト名" "DB_HOST" "localhost"
ask "DBポート番号" "DB_PORT" "3306"
ask "DB名" "DB_NAME" "your_database"
ask "DBユーザー名" "DB_USER" "backup_user"
read -s -p "DBパスワード: " DB_PASS
echo ""
[ -z "$DB_PASS" ] && DB_PASS="your_password_here"

ask "Laravelアプリのルートディレクトリ" "APP_DIR" "/var/www/your-app"
ask "ローカルバックアップ保存先" "BACKUP_LOCAL_DIR" "/backup"
ask "ローカル保持世代数" "KEEP_GENERATIONS" "30"

# --- 必要に応じて設定するもの (オプション) ---
echo ""
echo "[2/2] 必要に応じて設定する項目 (Enterでデフォルト/空)"
echo "----------------------------------------------------------"

ask "追加バックアップディレクトリ (スペース区切り)" "EXTRA_BACKUP_DIRS" ""
ask "サーバー設定バックアップ対象" "CONFIG_BACKUP_DIRS" "/etc/nginx /etc/php"
ask "ストレージバックエンド (b2/wasabi/s3/gdrive等)" "STORAGE_BACKEND" "local"

if [ "$STORAGE_BACKEND" != "local" ]; then
    ask "rclone リモート名" "STORAGE_REMOTE_NAME" "mybackup"
    ask "ストレージバケット名" "STORAGE_BUCKET" "your-backup-bucket"
    ask "バケット内プレフィックス" "STORAGE_PREFIX" "backups/server1"
fi

ask "通知先メールアドレス" "NOTIFY_EMAIL" ""
ask "通知用 Webhook URL" "WEBHOOK_URL" ""

# --- config.env の作成 ---
cat << EOF > "$CONFIG_FILE"
# ==========================================================
# バックアップ設定ファイル (Generated by setup_env.sh)
# ==========================================================

# ----- 環境識別 -----
SERVICE_NAME=$SERVICE_NAME
ENVIRONMENT=$ENVIRONMENT

# ----- データベース -----
DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASS='$DB_PASS'

# ----- バックアップ対象ディレクトリ -----
APP_DIR=$APP_DIR
EXTRA_BACKUP_DIRS="$EXTRA_BACKUP_DIRS"
CONFIG_BACKUP_DIRS="$CONFIG_BACKUP_DIRS"

# ----- ローカルバックアップ設定 -----
BACKUP_LOCAL_DIR=$BACKUP_LOCAL_DIR
KEEP_GENERATIONS=$KEEP_GENERATIONS

# ----- Cron スケジュール -----
CRON_MYSQL="0 2 * * *"
CRON_FILES="0 3 * * *"
CRON_SYNC="0 4 * * *"

# ----- ストレージバックエンド -----
STORAGE_BACKEND=$STORAGE_BACKEND
STORAGE_REMOTE_NAME=$STORAGE_REMOTE_NAME
STORAGE_BUCKET=$STORAGE_BUCKET
STORAGE_PREFIX=$STORAGE_PREFIX

# ----- 通知設定 -----
NOTIFY_EMAIL=$NOTIFY_EMAIL
WEBHOOK_URL=$WEBHOOK_URL

# ----- ログ設定 -----
LOG_DIR=/var/log/backup

# ----- その他設定 (詳細は config.env.example を参照) -----
TEST_DB_NAME=${DB_NAME}_test
CRON_TEST_RESTORE="0 5 * * *"
USE_SERVICE_VERSIONING=false
MASK_COLUMNS=""
MASK_DOMAIN="deve-liba.jp"
RESTORE_STOP_SERVICES=""
EOF

echo ""
echo "----------------------------------------------------------"
echo "$CONFIG_FILE を作成しました。"
echo "詳細な設定（S3キーやSendGrid API等）は直接ファイルを編集してください。"
echo "----------------------------------------------------------"
